FROM ubuntu:24.04

RUN apt update && apt install -y curl \
    && curl -fsSL -o /usr/local/bin/bazel \
       https://github.com/bazelbuild/bazel/releases/download/7.4.1/bazel-7.4.1-linux-x86_64 \
    && chmod +x /usr/local/bin/bazel \
    && ln -sf /usr/local/bin/bazel /usr/bin/bazel

# Install project dependencies
RUN apt update \
    && apt install -y \
    build-essential \
    gcc \
    g++ \
    python3 \
    git \
    clang \
    clang-tidy \
    cppcheck \
    valgrind

ARG UID=1000
ARG GID=1000
ARG USERNAME=skiplist
RUN userdel -r ubuntu 2>/dev/null || true && \
    groupadd -g ${GID} ${USERNAME} && \
    useradd -m -u ${UID} -g ${GID} -s /bin/bash ${USERNAME} && \
    mkdir -p /home/${USERNAME}/.cache && \
    mkdir -p /tmp/dazel && \
    chown -R ${UID}:${GID} /home/${USERNAME} && \
    chown -R ${UID}:${GID} /tmp

USER ${USERNAME}
WORKDIR /home/${USERNAME}

