###############################################################################
# Bazel now uses Bzlmod by default to manage external dependencies.
# Please consider migrating your external dependencies from WORKSPACE to MODULE.bazel.
#
# For more details, please check https://github.com/bazelbuild/bazel/issues/18958
###############################################################################

bazel_dep(name = "aspect_rules_lint", version = "1.2.2")
bazel_dep(name = "toolchains_llvm", version = "1.3.0")
bazel_dep(name = "googletest", version = "1.16.0")
bazel_dep(name = "rules_cc", version = "0.1.1")

# Hedron's Compile Commands Extractor for Bazel
# https://github.com/hedronvision/bazel-compile-commands-extractor
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
    commit = "0e990032f3c5a866e72615cf67e5ce22186dcb97",
    # Replace the commit hash (above) with the latest (https://github.com/hedronvision/bazel-compile-commands-extractor/commits/main).
    # Even better, set up Renovate and let it do the work for you (see "Suggestion: Updates" in the README).
)

llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm.toolchain(
    llvm_versions = {
        "": "17.0.6",
    },
)
use_repo(llvm, "llvm_toolchain", "llvm_toolchain_llvm")

bazel_dep(name = "bazel_clang_tidy", dev_dependency = True)
git_override(
    module_name = "bazel_clang_tidy",
    commit = "bd242cd869fad9f5644e0917971ab592b91cc3ae",
    remote = "https://github.com/wojciechmadry/bazel_clang_tidy.git",
)

bazel_dep(name = "bazel_cppcheck", dev_dependency = True)
git_override(
  module_name = "bazel_cppcheck",
  commit = "754843a7373b5fb55ddd32b501a786aba531daba",
  remote = "https://github.com/wojciechmadry/bazel_cppcheck.git",
)
