cc_test(
  name = "skip_list_tests",
  visibility = ["//visibility:public"],
  size = "small",
  srcs = ["initialization.cpp", "insertion.cpp", "clearing.cpp"],
  deps = ["@com_google_googletest//:gtest_main", "//include/skip_list:skip_list"],
)
